services:
  backend:
    build: 
      context: ./
    ports:
      -"8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://postgres:piyush@123@mydb:5434/mydb

  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
